import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import aiosmtplib
from app.config import settings

logger = logging.getLogger(__name__)

class EmailService:
    """
    Manages asynchronous email delivery via SMTP using aiosmtplib.
    """

    @classmethod
    async def _send_email(cls, to_email: str, subject: str, html_content: str):
        """Internal helper to dispatch emails using async SMTP connection."""
        # Ensure configuration is complete before trying to send
        if not all([settings.SMTP_HOST, settings.SMTP_PORT, settings.SMTP_USER, settings.SMTP_PASSWORD]):
            logger.warning("⚠️ SMTP settings are incomplete. Skipping email dispatch.")
            return

        message = MIMEMultipart("alternative")
        message["From"] = settings.SMTP_FROM_EMAIL or settings.SMTP_USER
        message["To"] = to_email
        message["Subject"] = subject

        # Attach html body
        message.attach(MIMEText(html_content, "html"))

        try:
            # Connect and send email asynchronously
            # If port is 465, use use_tls=True. If port is 587, use start_tls=True.
            use_tls = settings.SMTP_PORT == 465
            start_tls = settings.SMTP_PORT == 587 or settings.SMTP_PORT == 25
            
            async with aiosmtplib.SMTP(
                hostname=settings.SMTP_HOST,
                port=settings.SMTP_PORT,
                use_tls=use_tls
            ) as smtp:
                if start_tls:
                    await smtp.starttls()
                
                await smtp.login(settings.SMTP_USER, settings.SMTP_PASSWORD)
                await smtp.send_message(message)
                logger.info(f"📧 Email successfully sent to {to_email} (Subject: '{subject}')")
                
        except Exception as e:
            logger.error(f"❌ Failed to dispatch email to {to_email}: {e}")

    @classmethod
    async def send_admin_notification(cls, lead_data: dict):
        """
        Sends lead notification email to the admin with the requirements summary.
        """
        admin_email = settings.ADMIN_EMAIL
        namespace = lead_data.get("namespace", "default")
        subject = f"🚀 New Qualified Lead Captured - Namespace: [{namespace}]"

        personal_info = lead_data.get("personal_info", {})
        visitor_name = personal_info.get("name") or "Valued Visitor"
        visitor_email = personal_info.get("email") or "Not provided"

        # Generate HTML wrapping the markdown summary
        html_body = f"""
        <html>
        <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
            <div style="max-width: 600px; margin: 0 auto; border: 1px solid #ddd; padding: 20px; border-radius: 8px;">
                <h2 style="color: #4CAF50; border-bottom: 2px solid #4CAF50; padding-bottom: 10px;">New Qualified Lead</h2>
                <p>A new lead has been qualified by the chat assistant under tenant namespace: <strong>{namespace}</strong>.</p>
                
                <table style="width: 100%; border-collapse: collapse; margin: 15px 0;">
                    <tr style="background-color: #f2f2f2;">
                        <th style="text-align: left; padding: 8px; border: 1px solid #ddd;">Name</th>
                        <td style="padding: 8px; border: 1px solid #ddd;">{visitor_name}</td>
                    </tr>
                    <tr>
                        <th style="text-align: left; padding: 8px; border: 1px solid #ddd;">Email</th>
                        <td style="padding: 8px; border: 1px solid #ddd;">{visitor_email}</td>
                    </tr>
                </table>

                <div style="background-color: #fcfcfc; border-left: 4px solid #2196F3; padding: 15px; margin: 20px 0;">
                    <h3 style="margin-top: 0; color: #2196F3;">Project Discovery Summary</h3>
                    <div style="white-space: pre-wrap;">{lead_data.get("summary", "")}</div>
                </div>

                <p style="font-size: 0.8em; color: #666; margin-top: 30px;">
                    This email is auto-generated by the LangGraph Lead Qualification Assistant.
                </p>
            </div>
        </body>
        </html>
        """
        await cls._send_email(admin_email, subject, html_body)

    @classmethod
    async def send_visitor_thankyou(cls, visitor_email: str, company_name: str):
        """
        Sends a polite confirmation and thank you email to the visitor.
        """
        subject = f"Thank you for sharing your project details with {company_name}!"
        
        html_body = f"""
        <html>
        <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
            <div style="max-width: 600px; margin: 0 auto; border: 1px solid #ddd; padding: 20px; border-radius: 8px;">
                <h2 style="color: #2196F3;">Thank you!</h2>
                <p>Hi there,</p>
                <p>We've successfully received your project details and requirements through our website's project consultant chatbot.</p>
                <p>Our expert team at <strong>{company_name}</strong> is currently reviewing your needs. One of our technical representatives will get in touch with you shortly to schedule an initial discussion.</p>
                
                <p>Have a great day!</p>
                
                <div style="margin-top: 35px; border-top: 1px solid #ddd; padding-top: 15px;">
                    <strong>{company_name} Consultant Team</strong><br>
                    <a href="mailto:info@{company_name.lower().replace(' ', '')}.com" style="color: #2196F3;">Contact Support</a>
                </div>
            </div>
        </body>
        </html>
        """
        await cls._send_email(visitor_email, subject, html_body)
